### ISSUE TITLE
game not starting 

### ISSUE THREAD

**Issue by rakee2** [s1lentp4nther/Fuxia#1]
Im running NetBSD and the game is not working.

**Comment by s1lentp4nther** [comment]
I'm sorry for that. My game currently supports only Windows, Mac OS X and Linux systems. If you like to run the game on a linux PC try using a Debian like distro.

**Comment by s1lentp4nther** [comment]
> 
> 
> Im running NetBSD and the game is not working.

I'm sorry for that. My game currently supports only Windows, Mac OS X and Linux systems. If you like to run the game on a linux PC try using a Debian like distro.
